# Generated by Django 3.2 on 2021-04-26 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0003_auto_20200723_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('5e99711f-4215-4ef1-9ded-d25a311a6d17'), editable=False),
        ),
    ]
