# Generated by Django 3.1.3 on 2021-04-29 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0005_auto_20210428_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='topic',
            field=models.CharField(choices=[('arch', 'Architecture'), ('news', 'News'), ('heal', 'Health'), ('politics', 'Politics'), ('sports', 'Sports'), ('beauty', 'Beautytips')], max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('1622f36f-f6f0-4521-ab2b-ea332a16d613'), editable=False),
        ),
    ]
