# Generated by Django 3.1.3 on 2021-04-29 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0006_auto_20210429_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='topic',
            field=models.CharField(choices=[('arch', 'Architecture'), ('news', 'News'), ('heal', 'Health'), ('politics', 'Politics'), ('sports', 'Sports'), ('beauty', 'Beautytips'), ('other', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('76e759e3-93c6-4f04-aa86-13c1dab0cc2d'), editable=False),
        ),
    ]
